//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

public class TempCount extends DepthFirstVisitor {
   public int maxTemp = 0;
	
   /**
    * f0 -> "TEMP"
    * f1 -> IntegerLiteral()
    */
   public void visit(Temp n) {
      
	  if(Integer.decode(n.f1.f0.tokenImage) > maxTemp)
		  maxTemp = Integer.decode(n.f1.f0.tokenImage);
	   
	  n.f0.accept(this);
      n.f1.accept(this);
   }
}
