//
// Generated by JTB 1.3.2
//

package visitor;
import java.util.*;

class class_struct{
	HashMap<String, Integer> methods  = new HashMap<String, Integer>();
	HashMap<String, String>  method_class = new HashMap<String, String>();
	ArrayList<String> ordered_methods = new ArrayList<String>();
	int method_count = 0;
	
	HashMap<String, Integer> fields   = new HashMap<String, Integer>();
	HashMap<String, String>  ftype    = new HashMap<String, String>();
	ArrayList<String> ordered_fields  = new ArrayList<String>();
	int field_count  = 0;

	public int meth_count(){
		return method_count;
	}
	
	public int field_count(){
		return field_count;
	}
	
	public String method_i(int i){
		return method_class.get(ordered_methods.get(i))+"_"+ordered_methods.get(i);
	}
	
	public void display(){
		System.out.println("Fields: (in order)");
		System.out.println(ordered_fields);
		System.out.println("Methods: (in order)");
		for(String s: ordered_methods){
			System.out.println(method_class.get(s) + "_" + s);
		}
	}
	
	public void add_method(String s, String c){
		methods.put(s, method_count);
		ordered_methods.add(s);
		method_class.put(s, c);
		method_count++;
	}
	
	public void add_field(String s, String type){
		fields.put(s, field_count);
		ftype.put(s, type);
		ordered_fields.add(s);
		field_count++;
	}

	public class_struct copy(){
		class_struct copied = new class_struct();
		
		copied.method_count = method_count;
		copied.methods.putAll(methods);
		copied.method_class.putAll(method_class);
		copied.ordered_methods.addAll(ordered_methods);
		
		copied.field_count = field_count;
		copied.fields.putAll(fields);
		copied.ftype.putAll(ftype);
		copied.ordered_fields.addAll(ordered_fields);
		
		return copied;
	}
}